apiVersion: batch/v1
kind: Job
metadata:
  generateName: rotate-secret-presync-
  namespace: game-2048
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    spec:
      containers:
      - name: rotate-secret
        image: amazon/aws-cli
        env:
        - name: AWS_DEFAULT_REGION
          value: us-west-2  # Replace with your AWS region
        command: ["/bin/sh", "-c"]
        args:
        - |
          aws secretsmanager rotate-secret \
            --secret-id arn:aws:secretsmanager:us-west-2:889195446400:secret:dev/eks/pgsqlcreds-E7FH6A \
            --client-request-token 8bcda045-744c-e089-6aa0-a158f22be76e
      restartPolicy: Never
      serviceAccountName: nginx-sa
  backoffLimit: 2

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-secrets-deployment
  namespace: game-2048
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-secrets
  template:
    metadata:
      labels:
        app: nginx-secrets
        attr8: pre-sync-8
    spec:
      serviceAccountName: nginx-sa  # Ensure this service account has necessary permissions
      volumes:
        - name: secrets-store-inline
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: "aws-secrets-provider"
      containers:
        - name: nginx
          image: nginx:latest
          volumeMounts:
            - name: secrets-store-inline
              mountPath: "/mnt/secrets-store"
              readOnly: false
